import { initializeApp } from 'firebase/app';
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut } from 'firebase/auth';
import './style.css';

const config = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET, messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };
const configured = Object.values(config).every(Boolean); const auth = configured ? getAuth(initializeApp(config)) : null;
let user = null, journals = [], page = 'Dashboard', mode = 'reflect', messages = [], busy = false;
const root = document.querySelector('#root');
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;', "'":'&#39;','"':'&quot;' }[c]));
async function api(path, options = {}) { const token = await user.getIdToken(); const res = await fetch(path, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }); if (!res.ok) { const e = await res.json().catch(() => ({})); throw new Error(e.error?.message || 'Something went wrong.'); } return res.status === 204 ? null : res.json(); }
async function load() { journals = (await api('/api/journals')).journals; render(); }
function toast(text, error=false) { const n=document.createElement('div'); n.className=`toast ${error?'bad':''}`; n.textContent=text; document.body.append(n); setTimeout(()=>n.remove(),3200); }
const nav = ['Dashboard','Journal','Insights','Goals','Timeline','Privacy'];
function render() { if (!user) return landing(); const recent = journals.slice(0,4); const tags = Object.entries(journals.flatMap(j=>j.tags||[]).reduce((a,t)=>(a[t]=(a[t]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).slice(0,5); const content = page==='Journal'?journal():page==='Privacy'?privacy():page==='Timeline'?timeline():page==='Goals'?goals():page==='Insights'?insights():dashboard(recent,tags); root.innerHTML=`<div class="shell"><aside><a class="brand" href="#">◒ <span>MindVault</span></a><div class="nav">${nav.map(n=>`<button data-page="${n}" class="${page===n?'active':''}">${n}</button>`).join('')}</div><div class="account"><img src="${esc(user.photoURL||'')}" alt=""/><span>${esc(user.displayName||user.email)}</span><button id="signout">Sign out</button></div></aside><main>${content}</main></div>`; bind(); }
function dashboard(recent,tags){return `<header><div><p class="eyebrow">PRIVATE THINKING SPACE</p><h1>Good evening, ${esc((user.displayName||'there').split(' ')[0])} <span>✦</span></h1><p>Make room for the ideas that matter.</p></div><button class="primary" id="new">+ New reflection</button></header><section class="prompt"><h2>What is on your mind?</h2><p>Choose a way to begin. Your conversations stay connected to your account.</p><div class="modes">${[['reflect','Reflect','A place to untangle thoughts'],['brainstorm','Brainstorm','Find fresh angles'],['plan','Plan','Move from thought to action'],['free','Free chat','Follow your curiosity']].map(x=>`<button data-mode="${x[0]}"><b>${x[1]}</b><small>${x[2]}</small></button>`).join('')}</div></section><section class="grid"><div class="panel wide"><div class="section-title"><h2>Recent reflections</h2><button data-page="Journal">View all</button></div>${recent.length?recent.map(card).join(''):`<div class="empty">Your vault is ready. Start a reflection to build your personal timeline.</div>`}</div><div class="panel"><h2>Your journey</h2><div class="stats"><b>${journals.length}<small>reflections</small></b><b>${journals.flatMap(j=>j.goals||[]).length}<small>goals</small></b><b>${journals.flatMap(j=>j.actions||[]).length}<small>actions</small></b></div><h3>Recurring topics</h3><div class="tags">${tags.map(([t])=>`<span>#${esc(t)}</span>`).join('')||'<span>Waiting for your first reflection</span>'}</div></div></section>`}
const card=j=>`<article class="card" data-open="${j.id}"><span>${new Date(j.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><h3>${esc(j.title)}</h3><p>${esc(j.summary)}</p><div class="tags">${(j.tags||[]).slice(0,3).map(t=>`<i>#${esc(t)}</i>`).join('')}</div></article>`;
function journal(){return `<header><div><p class="eyebrow">JOURNAL</p><h1>Conversations that stay with you.</h1></div><button class="primary" id="new">+ New reflection</button></header>${messages.length?chat():`<section class="panel search"><input id="search" placeholder="Search title, summary, tags, or keywords"/><div id="results">${journals.length?journals.map(card).join(''):'<div class="empty">No saved reflections yet.</div>'}</div></section>`}`}
function chat(){return `<section class="chat panel"><div class="chathead"><div><p class="eyebrow">${mode.toUpperCase()}</p><h2>New conversation</h2></div><button id="clear">Clear</button></div><div class="messages">${messages.map(m=>`<div class="message ${m.role}">${esc(m.text)}</div>`).join('')}${busy?'<div class="typing">MindVault is thinking…</div>':''}</div><form id="send"><textarea id="message" placeholder="Write what’s on your mind…" ${busy?'disabled':''}></textarea><button class="primary" ${busy?'disabled':''}>Send ↗</button></form><div class="chatfoot"><span>Enter to send · Shift+Enter for new line</span><button class="primary" id="save" ${busy?'disabled':''}>Save reflection</button></div></section>`}
function insights(){return `<header><div><p class="eyebrow">INSIGHTS</p><h1>Patterns worth noticing.</h1></div></header><section class="panel list">${journals.flatMap(j=>(j.insights||[]).map(i=>`<article><b>${esc(j.title)}</b><p>${esc(i)}</p></article>`)).join('')||'<div class="empty">Insights will appear once you save a reflection.</div>'}</section>`}
function goals(){return `<header><div><p class="eyebrow">GOALS</p><h1>Small steps, consistently taken.</h1></div></header><section class="panel list">${journals.flatMap(j=>(j.goals||[]).map((g,i)=>`<article><b>Goal</b><p>${esc(g)}</p><small>Next: ${esc(j.actions?.[i]||'Return to this reflection')}</small></article>`)).join('')||'<div class="empty">Save a Plan reflection to create goals.</div>'}</section>`}
function timeline(){const groups={};journals.forEach(j=>{const k=new Date(j.createdAt).toLocaleDateString(undefined,{month:'long',year:'numeric'});(groups[k]??=[]).push(j)});return `<header><div><p class="eyebrow">TIMELINE</p><h1>Your thinking, over time.</h1></div></header><section class="timeline">${Object.entries(groups).map(([m,js])=>`<div><h2>${m}</h2>${js.map(j=>`<button data-open="${j.id}">● <b>${esc(j.title)}</b><small>${esc((j.tags||[]).join(' · '))}</small></button>`).join('')}</div>`).join('')||'<div class="empty">Your personal timeline begins with a saved reflection.</div>'}</section>`}
function privacy(){return `<header><div><p class="eyebrow">PRIVACY CENTER</p><h1>Your thoughts deserve boundaries.</h1><p>Privacy isn’t a feature added later. It’s how MindVault is built.</p></div></header><section class="panel privacy"><div>✓ Firebase Authentication<span>Only your verified account can access your data.</span></div><div>✓ User-isolated Firestore storage<span>Every journal operation is scoped to your Firebase UID.</span></div><div>✓ Server-side Gemini requests<span>Your Gemini credential never reaches the browser.</span></div><div>✓ Cloud Run + Secret Manager<span>Deployment uses HTTPS and managed secret injection.</span></div><hr/><button id="export">Export my data</button><button class="danger" id="deleteAll">Delete my journal data</button></section>`}
function landing(){root.innerHTML=`<main class="landing"><nav><a class="brand">◒ MindVault</a><span>Your thoughts. Your AI. Your private space.</span></nav><section class="hero"><p class="eyebrow">PERSONAL GEMINI JOURNAL</p><h1>Think freely.<br/><em>Reflect deeply.</em><br/>Keep it private.</h1><p>MindVault turns your conversations into meaningful insights, practical actions, and a private timeline of your growth.</p><button class="primary big" id="login">Continue with Google</button>${configured?'':'<small class="setup">Firebase client configuration is required before sign-in.</small>'}</section><section class="feature"><b>✦ AI-powered reflection</b><b>◒ Personal insights</b><b>⌁ Private journals</b><b>✓ Secure cloud architecture</b></section></main>`;document.querySelector('#login')?.addEventListener('click', async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch{toast('Sign-in could not be completed.',true)}})}
function bind(){document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{page=x.dataset.page;render()});document.querySelector('#signout').onclick=()=>signOut(auth);document.querySelector('#new').onclick=()=>{messages=[];mode='reflect';page='Journal';render();messages=[{role:'model',text:'I’m here to help you make space for what’s on your mind. Where would you like to begin?'}];render()};document.querySelectorAll('[data-mode]').forEach(x=>x.onclick=()=>{mode=x.dataset.mode;page='Journal';messages=[{role:'model',text:`${x.textContent.split(/(?=[A-Z])/)[0]} mode is ready. What would you like to explore?`}];render()});document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openJournal(x.dataset.open));document.querySelector('#search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#results').innerHTML=journals.filter(j=>[j.title,j.summary,...(j.tags||[]),...(j.keywords||[])].join(' ').toLowerCase().includes(q)).map(card).join('')||'<div class="empty">No matching reflections.</div>';document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openJournal(x.dataset.open))});document.querySelector('#send')?.addEventListener('submit',send);document.querySelector('#message')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();document.querySelector('#send').requestSubmit()}});document.querySelector('#clear')?.addEventListener('click',()=>{messages=[];render()});document.querySelector('#save')?.addEventListener('click',save);document.querySelector('#export')?.addEventListener('click',exportData);document.querySelector('#deleteAll')?.addEventListener('click',deleteAll)}
async function send(e){e.preventDefault();const el=document.querySelector('#message'), text=el.value.trim();if(!text||busy)return;messages.push({role:'user',text});busy=true;render();try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({mode,messages})});messages.push(r.message)}catch(e){toast(e.message,true)}finally{busy=false;render()}}
async function save(){if(messages.filter(m=>m.role==='user').length===0)return toast('Write a thought before saving.',true);busy=true;render();try{const r=await api('/api/journals/analyze',{method:'POST',body:JSON.stringify({mode,messages})});journals.unshift(r.journal);messages=[];toast('Reflection saved');render()}catch(e){toast(e.message,true);busy=false;render()}}
function openJournal(id){const j=journals.find(x=>x.id===id);if(!j)return;root.innerHTML=`<div class="detail"><button id="back">← Back</button><p class="eyebrow">${new Date(j.createdAt).toLocaleDateString()}</p><h1>${esc(j.title)}</h1><p class="summary">${esc(j.summary)}</p><div class="thought-action"><section><h2>Thought</h2>${j.messages.map(m=>`<p><b>${m.role==='user'?'You':'MindVault'}:</b> ${esc(m.text)}</p>`).join('')}</section><section><h2>Insight → Action → Goal</h2><h3>Insights</h3>${(j.insights||[]).map(x=>`<p>${esc(x)}</p>`).join('')}<h3>Actions</h3>${(j.actions||[]).map(x=>`<p>${esc(x)}</p>`).join('')}<h3>Goals</h3>${(j.goals||[]).map(x=>`<p>${esc(x)}</p>`).join('')}<div class="tags">${(j.tags||[]).map(t=>`<i>#${esc(t)}</i>`).join('')} <i>${esc(j.mood||'')}</i></div></section></div></div>`;document.querySelector('#back').onclick=()=>render()}
async function exportData(){try{const r=await api('/api/export');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.download='mindvault-export.json';a.click();URL.revokeObjectURL(a.href);toast('Your private export is ready.')}catch(e){toast(e.message,true)}}async function deleteAll(){if(!confirm('This permanently deletes your saved journal data. Continue?'))return;try{await api('/api/journals',{method:'DELETE'});journals=[];toast('Your saved journal data was deleted.');render()}catch(e){toast(e.message,true)}}
if(auth) onAuthStateChanged(auth, async u=>{user=u;if(u)try{await load()}catch(e){toast(e.message,true);render()}else render()});else landing();
